name: latexmk
on:
  push:
    branches: master
jobs:
  latexmk:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: yegor256/latexmk-action@0.10.9
        with:
          cmd: make
          depends: DEPENDS.txt
      - uses: JamesIves/github-pages-deploy-action@v4.5.0
        with:
          branch: gh-pages
          folder: package
          clean: false
